### ISSUE TITLE
Let inheriting classes using $writer and $reader

### ISSUE THREAD

**Issue by hexmode** [hakre/XMLReaderIterator#13]

**Comment by hakre** [comment]
Do you have a use-.case for that?

**Comment by hexmode** [comment]
hakre <notifications@github.com> writes:

> Do you have a use-.case for that?

https://github.com/MWStake/importWikiToNS/blob/master/src/MWStreamFilter.php#L162

**Comment by hakre** [comment]
As you have these in the constructor you can make your own privates, no need for the visibility change. This should also highlight to favor composition over inheritance.

**Comment by hexmode** [comment]
hakre <notifications@github.com> writes:

> As you have these in the constructor you can make your own privates,
> no need for the visibility change. This should also highlight to favor
> composition over inheritance.

Thanks for pointing that out.  It has been a bit since I thought about
this, but I recall coming to a similar conclusion (now that you mention
it) at some point.

This can be closed.

**Comment by hakre** [comment]
Nothing to thank for, please excuse my late feedback. I'll close for the moment, feel free to let me know if some of the functionality you need should be moved into the library (or is missing from your point of view).
