### ISSUE TITLE
Using the iterator after counting it

### ISSUE THREAD

**Issue by greg0ire** [hakre/XMLReaderIterator#7]
After using `iterator_count()` on an `XmlElementIterator` instance, the iterator is unusable (no iterations are done), probably because counting the elements implies reading the file. I tried calling `rewind()` on the iterator, but it does not seem to work…

**Comment by hakre** [comment]
You can call `rewind()` without an exception at the beginning or at the end of a file. But it won't rewind as **XMLReader** is forward only. So this is for the reason you named already. There is nothing to fix.

**Comment by greg0ire** [comment]
Ok, thanks for the answer.
